import type { Metadata } from "next"
import { cn } from "@config/utils"
import { GeistSans } from "geist/font/sans"

import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          GeistSans.className
        )}
      >
        {children}
      </body>
    </html>
  )
}
