name: 🐞 Bug Report
description: File a bug report for the Miti packages
title: '[bug]: '
labels: ['🐛 bug: unconfirmed', 'area:packages']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
        Note that the more precise you are, the quicker we will be able to investigate the bug.
        ```
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please describe the bug as clear and concise as possible, as well as the behavior you were expecting whilst encountering the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Describe how to reproduce your bug. Given the reproduction link above, what steps should we take to reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the bug here.
  - type: checkboxes
    attributes:
      label: 👨‍👧‍👦 Contributing
      description: We love contributors in any shape or form. Would you be willing to implement a fix?
      options:
        - label: 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/bhaskarkhoraja/miti/blob/main/.github/ISSUE_TEMPLATE/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
